version: '3.8'
services:
    # nginx:
    #     container_name: glinits_nginx
    #     image: nginx:1.21
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #     networks:
    #         - network
    #     restart: always
    psql:
        container_name: glinits_psql
        image: postgres:13
        environment:
        - POSTGRES_USER=lance
        - POSTGRES_PASSWORD=lance123
        - POSTGRES_DATABASE=glinits
        - POSTGRES_PORT=5432        
        volumes:
            - glinits_psql_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        expose:
            - "5432" 
        restart: always
        networks:
            - backend        
    app:
        container_name: glinits_app
        build:
            context: .
            dockerfile: Dockerfile
        image: glinits_app
        env_file:
            - .flaskenv
        # command: uwsgi --ini uwsgi.ini
        command: flask run --host 0.0.0.0

        # https://stackoverflow.com/a/45450456
        # Handy for debug!
        # command: tail -F anything
        depends_on:
            - psql
        ports:
            - "5000:5000"
        restart: always
        networks:
            - backend     
volumes:
    glinits_psql_data:

networks:
    backend:
